version: '3.8'

services:
  server:
    image: judge0/judge0:latest-extra
    env_file:
      - ./judge0.conf
    environment:
      ENABLE_ISOLATE: "false"
      ENABLE_AUTHENTICATION: "false"
      MAX_FILE_SIZE: "10485760"
      MAX_OUTPUT_SIZE: "10485760"
      MAX_MEMORY_LIMIT: "1024000"
      MAX_CPU_TIME: "10"
      MAX_EXECUTION_TIME: "10"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: YourJudge0PostgresPassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: YourVeryLongSecretKeyBaseThatIsAtLeast32CharactersLong
      RAILS_ENV: production
      DATABASE_URL: postgres://judge0:YourJudge0PostgresPassword@db:5432/judge0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - judge0-box:/box
    ports:
      - "2358:2358"
    privileged: true
    restart: always

  workers:
    image: judge0/judge0:latest-extra
    env_file:
      - ./judge0.conf
    environment:
      ENABLE_ISOLATE: "false"
      ENABLE_AUTHENTICATION: "false"
      MAX_FILE_SIZE: "10485760"
      MAX_OUTPUT_SIZE: "10485760"
      MAX_MEMORY_LIMIT: "1024000"
      MAX_CPU_TIME: "10"
      MAX_EXECUTION_TIME: "10"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: YourJudge0PostgresPassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: YourVeryLongSecretKeyBaseThatIsAtLeast32CharactersLong
      RAILS_ENV: production
      DATABASE_URL: postgres://judge0:YourJudge0PostgresPassword@db:5432/judge0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - judge0-box:/box
    privileged: true
    restart: always

  db:
    image: postgres:13
    env_file:
      - ./judge0.conf
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: YourJudge0PostgresPassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6
    env_file:
      - ./judge0.conf
    command: ["bash","-c","docker-entrypoint.sh --appendonly yes"]
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data:
  judge0-box:
